version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'futureme'
      MYSQL_USER: 'fmsa'
      MYSQL_PASSWORD: 'fmsa-1598753'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    volumes:
      - .:/app
    depends_on:
      - db
      - app
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile-celery-beat
    volumes:
      - .:/app
    depends_on:
      - db
      - app
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  db_data: {}
