version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'futureme'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    volumes:
      - .:/app
    depends_on:
      - db
      - app

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile-celery-beat
    volumes:
      - .:/app
    depends_on:
      - db
      - app

volumes:
  db_data: {}